import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789482000067 implements MigrationInterface {
    name = 'InitialSchema1789482000067'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."webhook_subscriptions_status_enum" AS ENUM('active', 'inactive', 'paused', 'disabled_by_admin')`);
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying(255) NOT NULL, "url" character varying(2048) NOT NULL, "secret" character varying(256) NOT NULL, "events" text NOT NULL, "status" "public"."webhook_subscriptions_status_enum" NOT NULL DEFAULT 'active', "description" text, "customHeaders" jsonb, "authToken" character varying(1024), "maxRetries" integer NOT NULL DEFAULT '5', "rateLimitPerMinute" integer NOT NULL DEFAULT '60', "totalDeliveries" integer NOT NULL DEFAULT '0', "totalFailures" integer NOT NULL DEFAULT '0', "lastDeliveredAt" TIMESTAMP WITH TIME ZONE, "lastFailedAt" TIMESTAMP WITH TIME ZONE, "lastEventAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e54e4e4200f7a74cbbdf764f51" ON "webhook_subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_deliveries_status_enum" AS ENUM('pending', 'success', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "webhook_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "webhookSubscriptionId" uuid NOT NULL, "eventType" character varying(100) NOT NULL, "payload" jsonb NOT NULL, "signature" character varying(128) NOT NULL, "status" "public"."webhook_deliveries_status_enum" NOT NULL DEFAULT 'pending', "httpStatusCode" integer, "responseBody" text, "errorMessage" text, "attemptNumber" integer NOT NULL DEFAULT '0', "maxRetries" integer NOT NULL DEFAULT '5', "durationMs" integer, "deliveredAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "nextRetryAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_535dd409947fb6d8fc6dfc0112a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16f897a9887e4372561fdcc155" ON "webhook_deliveries" ("webhookSubscriptionId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'analyst', 'arbitrator')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "displayName" character varying, "stellarPublicKey" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4b28a2c4b8bd96cce38ce2c6d" ON "users" ("stellarPublicKey") WHERE "stellarPublicKey" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."wallets_status_enum" AS ENUM('active', 'inactive', 'locked')`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "publicKey" character varying(56) NOT NULL, "encryptedSecretKey" text NOT NULL, "label" character varying(100), "status" "public"."wallets_status_enum" NOT NULL DEFAULT 'active', "isPrimary" boolean NOT NULL DEFAULT false, "cachedBalance" numeric(20,7) NOT NULL DEFAULT '0', "balanceSyncedAt" TIMESTAMP WITH TIME ZONE, "multisigThreshold" integer, "cosigners" jsonb, CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_84f794a0022d98193d9448d245" ON "wallets" ("publicKey") `);
        await queryRunner.query(`CREATE TYPE "public"."multisig_transactions_thresholdcategory_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."multisig_transactions_status_enum" AS ENUM('pending_signatures', 'ready', 'submitted', 'failed', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "multisig_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "walletId" uuid NOT NULL, "sourceAccount" character varying(56) NOT NULL, "unsignedXdr" text NOT NULL, "description" character varying(255), "requiredWeight" integer NOT NULL, "thresholdCategory" "public"."multisig_transactions_thresholdcategory_enum" NOT NULL DEFAULT 'medium', "status" "public"."multisig_transactions_status_enum" NOT NULL DEFAULT 'pending_signatures', "createdByUserId" uuid NOT NULL, "networkPassphrase" character varying(100) NOT NULL, "submittedTxHash" character varying(100), "failureReason" text, "expiresAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c7164ad0caba6ac38d0ec6ab182" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f27a53a4d2745de8a37dea0646" ON "multisig_transactions" ("walletId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6f542393aa19a51323cecd3f6" ON "multisig_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_168f1b91c2b550b587e9dd24f4" ON "multisig_transactions" ("walletId", "status") `);
        await queryRunner.query(`CREATE TABLE "multisig_signatures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "transactionId" uuid NOT NULL, "signerPublicKey" character varying(56) NOT NULL, "signatureXdr" text NOT NULL, "weight" integer NOT NULL, "signedByUserId" uuid, CONSTRAINT "PK_de2c3c065bef0e2643aae52c60c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96733ba6989bd2ef3d3c075123" ON "multisig_signatures" ("transactionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8504b7f392f6da1ee6a52d076" ON "multisig_signatures" ("transactionId", "signerPublicKey") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('payment', 'trade', 'listing_purchase', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "stellarTxHash" character varying, "userId" uuid, "type" "public"."transactions_type_enum" NOT NULL DEFAULT 'other', "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'pending', "fromAccount" character varying, "toAccount" character varying, "assetCode" character varying NOT NULL, "assetIssuer" character varying, "amount" numeric(30,7) NOT NULL, "listingId" uuid, "ledgerCloseTime" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_transactions_amount_positive" CHECK ("amount" > 0), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_256c7960dace26f2f271124dce" ON "transactions" ("stellarTxHash") WHERE "stellarTxHash" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_6bb58f2b6e30cb51a6504599f4" ON "transactions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da87c55b3bbbe96c6ed88ea7ee" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_user_status_created" ON "transactions" ("userId", "status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."batch_legs_status_enum" AS ENUM('pending', 'preparing', 'prepared', 'executing', 'executed', 'rolling_back', 'rolled_back', 'failed', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "batch_legs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "batchId" uuid NOT NULL, "orderIndex" integer NOT NULL, "dependencies" jsonb NOT NULL DEFAULT '[]', "contractId" character varying NOT NULL, "method" character varying NOT NULL, "args" jsonb NOT NULL DEFAULT '{}', "sourceAssetCode" character varying NOT NULL, "sourceAssetIssuer" character varying, "destAssetCode" character varying NOT NULL, "destAssetIssuer" character varying, "amount" numeric(30,7) NOT NULL, "minAmountOut" numeric(30,7) NOT NULL, "maxAmountOut" numeric(30,7), "status" "public"."batch_legs_status_enum" NOT NULL DEFAULT 'pending', "isConditional" boolean NOT NULL DEFAULT false, "conditionExpression" character varying, "conditionType" character varying, "expectedOutput" numeric(30,7), "actualOutput" numeric(30,7), "stellarTxHash" character varying, "errorMessage" text, "executionMetadata" jsonb, "preparedAt" TIMESTAMP WITH TIME ZONE, "executedAt" TIMESTAMP WITH TIME ZONE, "rolledBackAt" TIMESTAMP WITH TIME ZONE, "retryCount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_4089decaf512fc461460a22ca69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_34f326691e930a01d56953e5ed" ON "batch_legs" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_legs_status" ON "batch_legs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_legs_batch_id" ON "batch_legs" ("batchId") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_batches_status_enum" AS ENUM('created', 'preparing', 'prepared', 'committing', 'committed', 'rolling_back', 'rolled_back', 'failed', 'expired')`);
        await queryRunner.query(`CREATE TABLE "transaction_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying(128) NOT NULL, "status" "public"."transaction_batches_status_enum" NOT NULL DEFAULT 'created', "totalLegs" integer NOT NULL, "preparedLegs" integer NOT NULL DEFAULT '0', "committedLegs" integer NOT NULL DEFAULT '0', "completionRate" numeric(5,2), "sequenceNumber" bigint NOT NULL, "timeoutMs" integer NOT NULL DEFAULT '30000', "hasConditionals" boolean NOT NULL DEFAULT false, "resultSummary" jsonb, "errorMessage" text, "metadata" jsonb, "preparedAt" TIMESTAMP WITH TIME ZONE, "committedAt" TIMESTAMP WITH TIME ZONE, "failedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e94191060e5fd54cfbff50c3a97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6450098cfd48ef3437b4fe360" ON "transaction_batches" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_batches_created_at" ON "transaction_batches" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_batches_user_status" ON "transaction_batches" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."batch_audit_logs_action_enum" AS ENUM('batch_created', 'batch_prepare_started', 'batch_prepared', 'batch_commit_started', 'batch_committed', 'batch_rollback_started', 'batch_rolled_back', 'batch_failed', 'batch_expired', 'leg_prepared', 'leg_executed', 'leg_rolled_back', 'leg_failed', 'leg_retried', 'condition_evaluated', 'consistency_check_passed', 'consistency_check_failed', 'partial_fill_recovery')`);
        await queryRunner.query(`CREATE TABLE "batch_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "batchId" uuid NOT NULL, "legId" uuid, "action" "public"."batch_audit_logs_action_enum" NOT NULL, "actorId" character varying NOT NULL, "previousState" jsonb, "newState" jsonb, "metadata" jsonb, "durationMs" integer, CONSTRAINT "PK_a8eb59444e0dfbb44b1604f231d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6c484ae61066d9fbae721664c2" ON "batch_audit_logs" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_created_at" ON "batch_audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_action" ON "batch_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_batch_id" ON "batch_audit_logs" ("batchId") `);
        await queryRunner.query(`CREATE TABLE "trades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "makerOrderId" uuid NOT NULL, "takerOrderId" uuid NOT NULL, "makerUserId" uuid NOT NULL, "takerUserId" uuid NOT NULL, "assetCode" character varying NOT NULL, "assetIssuer" character varying, "quantity" numeric(30,7) NOT NULL, "price" numeric(30,7) NOT NULL, "stellarTxHash" character varying, "settled" boolean NOT NULL DEFAULT false, "settledAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c6d7c36a837411ba5194dc58595" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_423f3e8be79b7467f04d2466db" ON "trades" ("makerOrderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c674f97aaa8efd9582297a149" ON "trades" ("takerOrderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_114382727542adba2d2b90e0a5" ON "trades" ("makerUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37b1e010986c8656a127475397" ON "trades" ("takerUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_side_enum" AS ENUM('buy', 'sell')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_type_enum" AS ENUM('market', 'limit')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'open', 'partially_filled', 'filled', 'cancelled', 'expired', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "assetCode" character varying NOT NULL, "assetIssuer" character varying, "side" "public"."orders_side_enum" NOT NULL, "type" "public"."orders_type_enum" NOT NULL DEFAULT 'limit', "quantity" numeric(30,7) NOT NULL, "filledQuantity" numeric(30,7) NOT NULL, "price" numeric(30,7), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "expiresAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eadbc13a7dc33dfb702b14534e" ON "orders" ("assetCode") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_trails_action_enum" AS ENUM('order_created', 'order_updated', 'order_cancelled', 'trade_executed', 'trade_settled', 'order_rejected')`);
        await queryRunner.query(`CREATE TABLE "audit_trails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityId" uuid NOT NULL, "entityType" character varying NOT NULL, "action" "public"."audit_trails_action_enum" NOT NULL, "actorId" uuid NOT NULL, "previousState" jsonb NOT NULL, "newState" jsonb NOT NULL, "metadata" jsonb, CONSTRAINT "PK_91440e9d8998d3faf5f8cd6b9ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22feaf5fae928f9b0a49907927" ON "audit_trails" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."rate_limit_configs_tier_enum" AS ENUM('free', 'premium', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "rate_limit_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tier" "public"."rate_limit_configs_tier_enum" NOT NULL, "maxRequests" integer NOT NULL DEFAULT '100', "windowSizeSeconds" integer NOT NULL DEFAULT '60', "endpointPattern" character varying, "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9161d79952698317f7708737961" UNIQUE ("tier"), CONSTRAINT "PK_b030bece4024127ec07005697da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9161d79952698317f770873796" ON "rate_limit_configs" ("tier") `);
        await queryRunner.query(`CREATE TABLE "portfolio_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "snapshotDate" TIMESTAMP WITH TIME ZONE NOT NULL, "totalValueUsd" numeric(30,7) NOT NULL, "assetCount" integer NOT NULL, "holdings" jsonb NOT NULL, CONSTRAINT "PK_46c13ef40300b3a6d379488f53a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35bee2c1e38cf9298c2a503340" ON "portfolio_snapshots" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b69b3c3eb6503a959e90ce8a" ON "portfolio_snapshots" ("snapshotDate") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_channel_enum" AS ENUM('web_socket', 'in_app', 'email', 'sms', 'telegram', 'discord')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subject" text NOT NULL, "bodyTemplate" text NOT NULL, "htmlTemplate" text, "channel" "public"."notification_templates_channel_enum" NOT NULL DEFAULT 'email', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4118447024198c4ac2203a8218b" UNIQUE ("name"), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('web_socket', 'in_app', 'email', 'sms', 'telegram', 'discord')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('order_update', 'price_alert', 'portfolio_alert', 'system_notice')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_deliverystatus_enum" AS ENUM('pending', 'sent', 'failed', 'scheduled', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient" character varying NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'system_notice', "title" character varying(255), "message" text NOT NULL, "metadata" jsonb, "isRead" boolean NOT NULL DEFAULT false, "deliveryStatus" "public"."notifications_deliverystatus_enum" NOT NULL DEFAULT 'pending', "retryCount" integer NOT NULL DEFAULT '0', "scheduledAt" TIMESTAMP, "batchId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f32aebbf93c81e2e656c8a6bad" ON "notifications" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3e90d958270f67459f0663d52" ON "notifications" ("scheduledAt", "deliveryStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5097ae6510fafaebc7c8b352c" ON "notifications" ("recipient", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_df959b33c1ba4ad9ff2dc3c487" ON "notifications" ("recipient", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_30a545561c0718deb8390447a7" ON "notifications" ("recipient", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_channel_enum" AS ENUM('web_socket', 'in_app', 'email', 'sms', 'telegram', 'discord')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_subscribedtypes_enum" AS ENUM('order_update', 'price_alert', 'portfolio_alert', 'system_notice')`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "channel" "public"."notification_preferences_channel_enum" NOT NULL, "isEnabled" boolean NOT NULL DEFAULT true, "subscribedTypes" "public"."notification_preferences_subscribedtypes_enum" array NOT NULL DEFAULT '{order_update,price_alert,portfolio_alert,system_notice}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8facef03fbe2ee514e7fe7fe14a" UNIQUE ("userId", "channel"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."listings_status_enum" AS ENUM('active', 'sold', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "listings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "description" text, "assetCode" character varying NOT NULL, "assetIssuer" character varying, "amount" numeric(20,7) NOT NULL, "price" numeric(20,7) NOT NULL, "priceAssetCode" character varying NOT NULL DEFAULT 'XLM', "status" "public"."listings_status_enum" NOT NULL DEFAULT 'active', "sellerId" uuid NOT NULL, CONSTRAINT "PK_520ecac6c99ec90bcf5a603cdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc562bb50c44337df593cc14b3" ON "listings" ("assetCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a65b771bc8228047f2f78a091" ON "listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c98f5cd679fefeebac9ca98c7a" ON "listings" ("sellerId") `);
        await queryRunner.query(`CREATE TABLE "pool_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "poolId" uuid NOT NULL, "tvl" numeric(30,7) NOT NULL, "volume24h" numeric(30,7) NOT NULL, "feeRevenue24h" numeric(30,7) NOT NULL, "reserveA" numeric(30,7) NOT NULL, "reserveB" numeric(30,7) NOT NULL, "spotPrice" numeric(30,10) NOT NULL, "feeRate" numeric(10,8) NOT NULL, "snapshotAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8fd0645dd7ed78eacfd66711ef7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de11429da99c117cdfeff5ec17" ON "pool_snapshots" ("poolId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f98bcad411bf7ef524165171f7" ON "pool_snapshots" ("snapshotAt") `);
        await queryRunner.query(`CREATE TABLE "notification_analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ruleId" character varying, "ruleName" character varying, "severity" character varying, "category" character varying, "userId" character varying, "notificationId" character varying, "triggeredAt" TIMESTAMP WITH TIME ZONE, "processingLatency" integer, "userAction" character varying, "actionTimestamp" TIMESTAMP WITH TIME ZONE, "type" character varying, "totalEventsProcessed" bigint, "totalAlertsTriggered" bigint, "totalAlertsThrottled" bigint, "totalDeduplicated" bigint, "totalProcessingErrors" bigint, "averageProcessingTime" double precision, CONSTRAINT "PK_4da9dfd9d9590c3e89daee36044" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfc3f3efdd5ef21c496d293118" ON "notification_analytics" ("userId", "triggeredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c99674591cdfaff0b17390aead" ON "notification_analytics" ("severity", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb475b7f6c9b1df88b2c73927e" ON "notification_analytics" ("ruleId", "triggeredAt") `);
        await queryRunner.query(`CREATE TABLE "route_cache" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tokenIn" character varying NOT NULL, "tokenOut" character varying NOT NULL, "poolPath" jsonb NOT NULL, "expectedOutput" numeric(30,7) NOT NULL, "priceImpact" numeric(10,8) NOT NULL, "estimatedGas" numeric(20,0) NOT NULL, "confidence" numeric(5,4) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8ee2e2ae6dbf0800b0385d3b6bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_219067801fd908ef27703700d2" ON "route_cache" ("tokenIn") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccc877deab8cfea090c3362941" ON "route_cache" ("tokenOut") `);
        await queryRunner.query(`CREATE INDEX "IDX_da34a0d6d76e251178eafd6fa2" ON "route_cache" ("expiresAt") `);
        await queryRunner.query(`CREATE TYPE "public"."liquidity_pools_type_enum" AS ENUM('amm', 'order_book', 'stellar_dex')`);
        await queryRunner.query(`CREATE TYPE "public"."liquidity_pools_status_enum" AS ENUM('active', 'inactive', 'deprecated')`);
        await queryRunner.query(`CREATE TABLE "liquidity_pools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" "public"."liquidity_pools_type_enum" NOT NULL, "status" "public"."liquidity_pools_status_enum" NOT NULL DEFAULT 'active', "assetCodeA" character varying NOT NULL, "assetIssuerA" character varying, "assetCodeB" character varying NOT NULL, "assetIssuerB" character varying, "tvl" numeric(30,7) NOT NULL DEFAULT '0', "feeRate" numeric(10,8) NOT NULL DEFAULT '0', "volume24h" numeric(30,7) NOT NULL DEFAULT '0', "feeRevenue24h" numeric(30,7) NOT NULL DEFAULT '0', "maxInputSize" numeric(30,7), "onChainAddress" character varying, "lastRefreshedAt" TIMESTAMP WITH TIME ZONE, "config" jsonb, CONSTRAINT "PK_b8aa2e33835704c8a170c5cd404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98ae24c5ad8e4c6200ea1a9856" ON "liquidity_pools" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_8073479b36f9a5ead3a3616be3" ON "liquidity_pools" ("assetCodeA") `);
        await queryRunner.query(`CREATE INDEX "IDX_9859e6b4f69f733f09e017f1e7" ON "liquidity_pools" ("assetCodeB") `);
        await queryRunner.query(`CREATE TYPE "public"."arbitrage_opportunities_status_enum" AS ENUM('detected', 'simulated', 'executed', 'expired', 'invalidated')`);
        await queryRunner.query(`CREATE TABLE "arbitrage_opportunities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "baseAsset" character varying NOT NULL, "quoteAsset" character varying NOT NULL, "cyclePools" jsonb NOT NULL, "estimatedProfit" numeric(30,7) NOT NULL, "maxProfitableSize" numeric(30,7) NOT NULL, "spreadPercent" numeric(10,6) NOT NULL, "estimatedGasCost" numeric(20,0) NOT NULL, "status" "public"."arbitrage_opportunities_status_enum" NOT NULL DEFAULT 'detected', "detectedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_1309d80ee235654cb084b561252" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_018cf7e53f7919c324a7707da1" ON "arbitrage_opportunities" ("baseAsset") `);
        await queryRunner.query(`CREATE INDEX "IDX_e849f726c62c2de31e5d83d0c4" ON "arbitrage_opportunities" ("detectedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_accounts_type_enum" AS ENUM('standard', 'time_locked', 'milestone_based', 'trust_account')`);
        await queryRunner.query(`CREATE TYPE "public"."escrow_accounts_status_enum" AS ENUM('pending', 'awaiting_funding', 'funded', 'approved', 'partially_released', 'settled', 'refunded', 'disputed', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "escrow_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "creatorId" uuid NOT NULL, "escrowAddress" character varying(56), "type" "public"."escrow_accounts_type_enum" NOT NULL DEFAULT 'standard', "status" "public"."escrow_accounts_status_enum" NOT NULL DEFAULT 'pending', "requiredSignatures" integer NOT NULL, "totalSignatories" integer NOT NULL, "assetCode" character varying(12) NOT NULL, "assetIssuer" character varying(56), "amount" numeric(30,7) NOT NULL, "releasedAmount" numeric(30,7) NOT NULL DEFAULT '0', "feeAmount" numeric(30,7) NOT NULL DEFAULT '0', "settlementDeadline" TIMESTAMP WITH TIME ZONE, "timeLockExpiry" TIMESTAMP WITH TIME ZONE, "description" text, "tradeId" uuid, "disputeId" uuid, "fundingTxHash" character varying(100), "settlementTxHash" character varying(100), "fundedAt" TIMESTAMP WITH TIME ZONE, "settledAt" TIMESTAMP WITH TIME ZONE, "refundedAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_4d065b88217295bb812ff7b2af2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc65c37fb330fa0139e9fb7cbc" ON "escrow_accounts" ("creatorId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d63194481c463866b27b3c27ba" ON "escrow_accounts" ("escrowAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_058dc076c4c41196ed086f0fa0" ON "escrow_accounts" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fb90845036be42987113ab96d" ON "escrow_accounts" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_signatories_role_enum" AS ENUM('creator', 'counterparty', 'trustee', 'institutional_rep', 'admin')`);
        await queryRunner.query(`CREATE TABLE "escrow_signatories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "escrowAccountId" uuid NOT NULL, "userId" uuid NOT NULL, "publicKey" character varying(56) NOT NULL, "role" "public"."escrow_signatories_role_enum" NOT NULL DEFAULT 'counterparty', "hasApproved" boolean NOT NULL DEFAULT false, "approvedAt" TIMESTAMP WITH TIME ZONE, "revokedAt" TIMESTAMP WITH TIME ZONE, "approvalIpAddress" character varying(45), CONSTRAINT "PK_06c0c81fb34842fa3930855d3b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7640e3281b452444b4f80276cf" ON "escrow_signatories" ("escrowAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f04f3909ee01de9a7ce65a50b" ON "escrow_signatories" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3e6c59b6f18eb94d687931f918" ON "escrow_signatories" ("escrowAccountId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_timeline_eventtype_enum" AS ENUM('escrow_created', 'signatory_added', 'signatory_approved', 'signatory_revoked', 'escrow_funded', 'milestone_added', 'milestone_completed', 'partial_release', 'escrow_settled', 'escrow_refunded', 'escrow_expired', 'escrow_cancelled', 'dispute_flagged', 'dispute_resolved', 'timeout_triggered', 'signature_threshold_reached')`);
        await queryRunner.query(`CREATE TABLE "escrow_timeline" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "escrowAccountId" uuid NOT NULL, "eventType" "public"."escrow_timeline_eventtype_enum" NOT NULL, "actorId" uuid NOT NULL, "description" text, "metadata" jsonb, CONSTRAINT "PK_b48b8f60731979985dbafa909cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac5ba8dd168f451627bc6d1454" ON "escrow_timeline" ("escrowAccountId") `);
        await queryRunner.query(`CREATE TABLE "escrow_milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "escrowAccountId" uuid NOT NULL, "title" character varying(200) NOT NULL, "description" text, "orderIndex" integer NOT NULL, "amount" numeric(30,7) NOT NULL, "isCompleted" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP WITH TIME ZONE, "completedBy" uuid, "releaseTxHash" character varying(100), CONSTRAINT "PK_fa6bd455d3bec9a08c0fa066743" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c4b06882bfec7bf138c7c8210" ON "escrow_milestones" ("escrowAccountId") `);
        await queryRunner.query(`CREATE TABLE "dispute_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "disputeId" uuid NOT NULL, "senderId" uuid NOT NULL, "content" text NOT NULL, "isInternal" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8826f78d556a1846f8cbad5ed05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_288e9a3fe13cfe14abe9824e9c" ON "dispute_messages" ("disputeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e154dd9c8d78610a275b5c7253" ON "dispute_messages" ("senderId") `);
        await queryRunner.query(`CREATE TYPE "public"."disputes_classification_enum" AS ENUM('non_delivery', 'wrong_amount', 'fraud', 'system_error')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('filed', 'under_review', 'investigation', 'arbitration', 'resolved', 'appealed', 'closed', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_resolutiontype_enum" AS ENUM('refund', 'settlement', 'reversal', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tradeId" uuid NOT NULL, "complainantId" uuid NOT NULL, "respondentId" uuid NOT NULL, "classification" "public"."disputes_classification_enum" NOT NULL, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'filed', "description" text NOT NULL, "arbitratorId" uuid, "resolutionType" "public"."disputes_resolutiontype_enum", "decisionReasoning" text, "resolutionAmount" numeric(30,7), "appealed" boolean NOT NULL DEFAULT false, "similarDisputesFlagged" boolean NOT NULL DEFAULT false, "enforcementExecuted" boolean NOT NULL DEFAULT false, "initialReviewDeadline" TIMESTAMP WITH TIME ZONE NOT NULL, "resolutionDeadline" TIMESTAMP WITH TIME ZONE NOT NULL, "initialReviewCompletedAt" TIMESTAMP WITH TIME ZONE, "resolvedAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c71270511d986442bb1813647a" ON "disputes" ("tradeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da437e54ac24659ff46aff18c0" ON "disputes" ("complainantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bedde3922ec76bcc4b4c1bd93" ON "disputes" ("respondentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ea46f4f2225f38d127063c367" ON "disputes" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."dispute_timeline_eventtype_enum" AS ENUM('dispute_filed', 'status_changed', 'evidence_submitted', 'evidence_validated', 'arbitrator_assigned', 'message_sent', 'decision_made', 'appeal_filed', 'enforcement_executed', 'sla_breach')`);
        await queryRunner.query(`CREATE TABLE "dispute_timeline" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "disputeId" uuid NOT NULL, "eventType" "public"."dispute_timeline_eventtype_enum" NOT NULL, "actorId" uuid NOT NULL, "description" text, "metadata" jsonb, CONSTRAINT "PK_62c1a2e7f15be3da4f84e0ed341" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3031a37a2cb313f668ed6fc69" ON "dispute_timeline" ("disputeId") `);
        await queryRunner.query(`CREATE TYPE "public"."arbitrators_expertise_enum" AS ENUM('non_delivery', 'wrong_amount', 'fraud', 'system_error', 'general')`);
        await queryRunner.query(`CREATE TABLE "arbitrators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "expertise" "public"."arbitrators_expertise_enum" array NOT NULL DEFAULT '{general}', "isAvailable" boolean NOT NULL DEFAULT true, "activeDisputeCount" integer NOT NULL DEFAULT '0', "maxActiveDisputes" integer NOT NULL DEFAULT '10', "totalResolved" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_58f7cd1e47b60a78a5ea82bb342" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a7db7f4151d049652d8fe5acc" ON "arbitrators" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."dispute_evidence_status_enum" AS ENUM('pending', 'validated', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "dispute_evidence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "disputeId" uuid NOT NULL, "uploadedById" uuid NOT NULL, "fileName" character varying NOT NULL, "mimeType" character varying NOT NULL, "fileSize" integer NOT NULL, "storagePath" character varying NOT NULL, "description" text, "status" "public"."dispute_evidence_status_enum" NOT NULL DEFAULT 'pending', "validationResult" jsonb, CONSTRAINT "PK_6b34f65b55c04db5a6929bff0ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_741a5a7010d0c03f8122d6d61b" ON "dispute_evidence" ("disputeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce56d3bfad4feb1d3252c51384" ON "dispute_evidence" ("uploadedById") `);
        await queryRunner.query(`CREATE TYPE "public"."compliance_configs_region_enum" AS ENUM('us', 'eu', 'uk', 'asia_pacific', 'global')`);
        await queryRunner.query(`CREATE TABLE "compliance_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "region" "public"."compliance_configs_region_enum" NOT NULL, "displayName" character varying(128) NOT NULL, "amlTransactionThreshold" numeric(30,7) NOT NULL DEFAULT '10000', "dailyVolumeThreshold" numeric(30,7) NOT NULL DEFAULT '50000', "blockThresholdScore" integer NOT NULL DEFAULT '80', "enhancedDueDiligenceScore" integer NOT NULL DEFAULT '60', "flagThresholdScore" integer NOT NULL DEFAULT '40', "maxDailyTransactions" integer NOT NULL DEFAULT '50', "kycExpiryMonths" integer NOT NULL DEFAULT '12', "institutionalRequiredLevel" character varying(32) NOT NULL DEFAULT 'institutional', "requireSarForCritical" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "customRules" jsonb, CONSTRAINT "UQ_2e9040aac7adaa82e79053c2998" UNIQUE ("region"), CONSTRAINT "PK_724b46127fe624c92c84e1ff888" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e9040aac7adaa82e79053c299" ON "compliance_configs" ("region") `);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_level_enum" AS ENUM('unverified', 'standard', 'enhanced', 'institutional')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_risklevel_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "kyc_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "level" "public"."kyc_verifications_level_enum" NOT NULL DEFAULT 'unverified', "riskLevel" "public"."kyc_verifications_risklevel_enum" NOT NULL DEFAULT 'low', "riskScore" integer NOT NULL DEFAULT '0', "region" character varying(2), "transactionsBlocked" boolean NOT NULL DEFAULT false, "blockReason" text, "lastVerifiedAt" TIMESTAMP WITH TIME ZONE, "verificationExpiry" TIMESTAMP WITH TIME ZONE, "thirdPartyRefId" character varying(256), "complianceNotes" text, "metadata" jsonb, CONSTRAINT "PK_57b7c6b141dd225ce5dc95d7fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f71e34495dae27087b5773b35b" ON "kyc_verifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "compliance_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "performedBy" uuid, "performedByRole" character varying(32), "targetUserId" uuid NOT NULL, "action" character varying(64) NOT NULL, "description" text NOT NULL, "entityType" character varying(64), "entityId" character varying(128), "previousState" jsonb, "newState" jsonb, "ipAddress" character varying(64), "metadata" jsonb, CONSTRAINT "PK_d8fc162802a31ed9f4f3f8cb854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3dc59243d0fc921b9f82074ffb" ON "compliance_audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_95d5fd0497c4395f8737a22f14" ON "compliance_audit_logs" ("performedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffbd41c9c75a25e6c5e2332ae5" ON "compliance_audit_logs" ("targetUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_20cefd620ec4e2ab8837079b9f" ON "compliance_audit_logs" ("action") `);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_documenttype_enum" AS ENUM('id_verification', 'address_proof', 'beneficial_ownership')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_status_enum" AS ENUM('pending', 'verified', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "kyc_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "kycVerificationId" uuid NOT NULL, "documentType" "public"."kyc_documents_documenttype_enum" NOT NULL, "status" "public"."kyc_documents_status_enum" NOT NULL DEFAULT 'pending', "fileName" character varying(256) NOT NULL, "mimeType" character varying(128) NOT NULL, "fileSize" integer NOT NULL, "storagePath" character varying(512) NOT NULL, "fileHash" character varying(128) NOT NULL, "encryptionKeyId" character varying(256), "reviewedBy" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, "metadata" jsonb, CONSTRAINT "PK_02e49877f1578e6285f84e57ab6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5582c3140c9cdbc6e5f61e0577" ON "kyc_documents" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cf6121019cef068e24a0130ea" ON "kyc_documents" ("kycVerificationId") `);
        await queryRunner.query(`CREATE TYPE "public"."aml_flags_risklevel_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."aml_flags_status_enum" AS ENUM('pending', 'reviewing', 'cleared', 'confirmed')`);
        await queryRunner.query(`CREATE TABLE "aml_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "transactionId" uuid, "riskLevel" "public"."aml_flags_risklevel_enum" NOT NULL DEFAULT 'medium', "status" "public"."aml_flags_status_enum" NOT NULL DEFAULT 'pending', "triggerRule" character varying(128) NOT NULL, "description" text NOT NULL, "riskScore" integer NOT NULL DEFAULT '0', "transactionAmount" numeric(30,7), "reviewedBy" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "resolutionNotes" text, "evidence" jsonb, "sarFiled" boolean NOT NULL DEFAULT false, "sarReference" character varying(128), CONSTRAINT "PK_83c7d5985009fd590f368897bb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0c6f2e60a2224c2fd9731c683" ON "aml_flags" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb2201163ed66e787e40ac52a8" ON "aml_flags" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_df7123a42ef2f3e669efda22ea" ON "aml_flags" ("triggerRule") `);
        await queryRunner.query(`CREATE TABLE "indexer_state" ("key" character varying NOT NULL, "value" text, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_4722c8d58787c0fa3ecfca6ea1a" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "indexed_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "sequenceNumber" bigint NOT NULL, "ledgerSequence" integer NOT NULL, "eventType" character varying NOT NULL, "transactionHash" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "sourceAccount" character varying NOT NULL, "destinationAccount" character varying, "contractId" character varying, "methodName" character varying, "assetCode" character varying, "assetIssuer" character varying, "amount" character varying, "topics" jsonb, "value" jsonb, "normalizedData" jsonb, "raw" jsonb, "invalidated" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_efed6f796c0f8591da1d7b02573" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50dc6b0d080b212e6c673eebd1" ON "indexed_events" ("contractId", "eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f53d83210438a6f59c37f2d0bd" ON "indexed_events" ("ledgerSequence", "eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_e03a35937aac0e95c8e2044ace" ON "indexed_events" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_e73ac51e27bcbdcd69b04b3b8a" ON "indexed_events" ("sourceAccount") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d0286e44d9f8264a5654e2908" ON "indexed_events" ("contractId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9b97e1a0ea4e516b78c4c2774" ON "indexed_events" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_b94e3e40e5b3648143a7359edd" ON "indexed_events" ("ledgerSequence") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_44ad06e72039c41b20d78244a4" ON "indexed_events" ("sequenceNumber") `);
        await queryRunner.query(`CREATE TABLE "stellar_auth_challenges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "nonce" character varying NOT NULL, "publicKey" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_71b3e4311b18e3557058a9543d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_62a6c9da9db0d5552edeff73c4" ON "stellar_auth_challenges" ("nonce") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b2a7195ecfb421efb3738c6c4" ON "stellar_auth_challenges" ("publicKey") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "deviceHint" character varying, "ipAddress" character varying, "userAgent" character varying, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6a19d4b4f6c62dcd29daa497e" ON "password_reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "keyHash" character varying NOT NULL, "keyPreview" character varying, "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "scopes" jsonb, CONSTRAINT "UQ_5457f77c4528c36c3d810bf6b70" UNIQUE ("name"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6c2e267ae764a9413b863a2934" ON "api_keys" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_audit_logs_eventtype_enum" AS ENUM('register', 'login_success', 'login_failed', 'logout', 'token_refresh', 'token_revoked', 'password_reset_request', 'password_reset_success', 'api_key_created', 'api_key_revoked', 'stellar_auth_challenge', 'stellar_auth_success', 'stellar_auth_failed', 'oauth_login_success', 'account_locked')`);
        await queryRunner.query(`CREATE TABLE "auth_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid, "eventType" "public"."auth_audit_logs_eventtype_enum" NOT NULL, "ipAddress" character varying, "userAgent" character varying, "metadata" jsonb, "success" boolean NOT NULL DEFAULT true, "failureReason" character varying, CONSTRAINT "PK_be11d76bd32256469e1a14a97db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f11cf3b259c89a8395b6c94df" ON "auth_audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c1c1b7eaffecf09aca11859ca" ON "auth_audit_logs" ("eventType") `);
        await queryRunner.query(`CREATE TYPE "public"."assets_status_enum" AS ENUM('active', 'deprecated')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying NOT NULL, "name" character varying, "description" character varying, "imageUrl" character varying, "status" "public"."assets_status_enum" NOT NULL DEFAULT 'active', "isTradeable" boolean NOT NULL DEFAULT true, "deprecationDate" TIMESTAMP WITH TIME ZONE, "issuer" character varying, "isNative" boolean NOT NULL DEFAULT false, "domain" character varying, "holders" bigint NOT NULL DEFAULT '0', "totalSupply" numeric(30,7) NOT NULL DEFAULT '0', "isVerified" boolean NOT NULL DEFAULT true, "lastIndexedAt" TIMESTAMP WITH TIME ZONE, "migratedToId" uuid, CONSTRAINT "UQ_asset_code_issuer" UNIQUE ("code", "issuer"), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bff60c1b89bff7edff592d85ea" ON "assets" ("code") `);
        await queryRunner.query(`CREATE TABLE "trustlines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "balance" numeric(30,7) NOT NULL, "limit" numeric(30,7) NOT NULL, "userId" uuid, "assetId" uuid, CONSTRAINT "PK_303fabe3ecb4c97482ed869bbc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blockchain_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uniqueId" character varying NOT NULL, "eventType" character varying NOT NULL, "transactionHash" character varying NOT NULL, "ledger" numeric NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "sourceAccount" character varying NOT NULL, "destinationAccount" character varying, "assetCode" character varying NOT NULL, "assetIssuer" character varying, "amount" numeric(30,7) NOT NULL, "raw" jsonb, "invalidated" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_05c74fec5cca18164ba7511427c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39dec781aff30b8d0666eadbcb" ON "blockchain_events" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5fbd31d9df1bb2a59f4cc232d" ON "blockchain_events" ("ledger", "eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b9c972c53223cb12f76c8776f" ON "blockchain_events" ("sourceAccount", "ledger") `);
        await queryRunner.query(`CREATE INDEX "IDX_f385623f51a58d5ed2428a9c60" ON "blockchain_events" ("transactionHash", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "saved_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying(255) NOT NULL, "reportType" character varying(50) NOT NULL, "format" character varying(20) NOT NULL, "status" character varying(20) NOT NULL, "dateFrom" TIMESTAMP WITH TIME ZONE NOT NULL, "dateTo" TIMESTAMP WITH TIME ZONE NOT NULL, "filters" jsonb, "metrics" jsonb, "dimensions" jsonb, "fileUrl" text, "fileSize" bigint, "completedAt" TIMESTAMP WITH TIME ZONE, "errorMessage" text, "isScheduled" boolean NOT NULL DEFAULT false, "scheduleCron" character varying, "nextRunAt" TIMESTAMP WITH TIME ZONE, "lastRunAt" TIMESTAMP WITH TIME ZONE, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ab9983395681688e8d042fbe12e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_821d8e4edbf8e11f9fd8bb8b13" ON "saved_reports" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_category_enum" AS ENUM('user_action', 'admin_action', 'system_event', 'data_change', 'security')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_outcome_enum" AS ENUM('success', 'failure')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "category" "public"."audit_logs_category_enum" NOT NULL DEFAULT 'system_event', "action" character varying(128) NOT NULL, "outcome" "public"."audit_logs_outcome_enum" NOT NULL DEFAULT 'success', "userId" uuid, "userRole" character varying(32), "resourceType" character varying(64), "resourceId" character varying(128), "httpMethod" character varying(8), "path" character varying(512), "statusCode" integer, "durationMs" integer, "ipAddress" character varying(64), "userAgent" character varying(256), "requestId" character varying(64), "beforeState" jsonb, "afterState" jsonb, "metadata" jsonb, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a0324bcdc1e155445c66213af" ON "audit_logs" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3efbfd507134492f264a19b9c" ON "audit_logs" ("requestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_09013c9e439b8761355df5f827" ON "audit_logs" ("resourceType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ec936941eb8556fcd7a1f0eae" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e589da8f9e9326ee0d01a028" ON "audit_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "analytics_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metricType" character varying(50) NOT NULL, "aggregation" character varying(20) NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "value" numeric(30,7) NOT NULL, "dimensions" jsonb, "assetCode" character varying, "assetIssuer" character varying, "userId" character varying, "source" character varying, "poolId" character varying, "pairCode" character varying, "traderId" character varying, "metadata" jsonb, CONSTRAINT "PK_6710bc54d5d07642f917914942d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_785a09b65304d32ac1d7998c37" ON "analytics_metrics" ("metricType", "aggregation", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "user_segments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "description" text, "segmentType" character varying(20) NOT NULL, "filterCriteria" jsonb, "userIds" uuid array NOT NULL DEFAULT '{}', "userCount" integer NOT NULL DEFAULT '0', "lastCalculatedAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdBy" uuid, CONSTRAINT "PK_a6e2b9ccd13727fe23d00c4d99c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c3279e97ff3ca1e0b9abc3dd0" ON "user_segments" ("createdBy") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "multisig_transactions" ADD CONSTRAINT "FK_f27a53a4d2745de8a37dea0646c" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "multisig_signatures" ADD CONSTRAINT "FK_96733ba6989bd2ef3d3c0751232" FOREIGN KEY ("transactionId") REFERENCES "multisig_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_c98f5cd679fefeebac9ca98c7a5" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_signatories" ADD CONSTRAINT "FK_7640e3281b452444b4f80276cff" FOREIGN KEY ("escrowAccountId") REFERENCES "escrow_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_milestones" ADD CONSTRAINT "FK_4c4b06882bfec7bf138c7c8210d" FOREIGN KEY ("escrowAccountId") REFERENCES "escrow_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_6c2e267ae764a9413b863a29342" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "FK_7f11cf3b259c89a8395b6c94df2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_faeeea0c006268aca0ad236eb24" FOREIGN KEY ("migratedToId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trustlines" ADD CONSTRAINT "FK_2cf39214c55a11e3b454985ac96" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trustlines" ADD CONSTRAINT "FK_e069a294421187217e668aaa4c1" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "trustlines" DROP CONSTRAINT "FK_e069a294421187217e668aaa4c1"`);
        await queryRunner.query(`ALTER TABLE "trustlines" DROP CONSTRAINT "FK_2cf39214c55a11e3b454985ac96"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_faeeea0c006268aca0ad236eb24"`);
        await queryRunner.query(`ALTER TABLE "auth_audit_logs" DROP CONSTRAINT "FK_7f11cf3b259c89a8395b6c94df2"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_6c2e267ae764a9413b863a29342"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "escrow_milestones" DROP CONSTRAINT "FK_4c4b06882bfec7bf138c7c8210d"`);
        await queryRunner.query(`ALTER TABLE "escrow_signatories" DROP CONSTRAINT "FK_7640e3281b452444b4f80276cff"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_c98f5cd679fefeebac9ca98c7a5"`);
        await queryRunner.query(`ALTER TABLE "multisig_signatures" DROP CONSTRAINT "FK_96733ba6989bd2ef3d3c0751232"`);
        await queryRunner.query(`ALTER TABLE "multisig_transactions" DROP CONSTRAINT "FK_f27a53a4d2745de8a37dea0646c"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c3279e97ff3ca1e0b9abc3dd0"`);
        await queryRunner.query(`DROP TABLE "user_segments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_785a09b65304d32ac1d7998c37"`);
        await queryRunner.query(`DROP TABLE "analytics_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e589da8f9e9326ee0d01a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec936941eb8556fcd7a1f0eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09013c9e439b8761355df5f827"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3efbfd507134492f264a19b9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a0324bcdc1e155445c66213af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_outcome_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_821d8e4edbf8e11f9fd8bb8b13"`);
        await queryRunner.query(`DROP TABLE "saved_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f385623f51a58d5ed2428a9c60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b9c972c53223cb12f76c8776f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5fbd31d9df1bb2a59f4cc232d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39dec781aff30b8d0666eadbcb"`);
        await queryRunner.query(`DROP TABLE "blockchain_events"`);
        await queryRunner.query(`DROP TABLE "trustlines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bff60c1b89bff7edff592d85ea"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c1c1b7eaffecf09aca11859ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f11cf3b259c89a8395b6c94df"`);
        await queryRunner.query(`DROP TABLE "auth_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."auth_audit_logs_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c2e267ae764a9413b863a2934"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a19d4b4f6c62dcd29daa497e"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b2a7195ecfb421efb3738c6c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62a6c9da9db0d5552edeff73c4"`);
        await queryRunner.query(`DROP TABLE "stellar_auth_challenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44ad06e72039c41b20d78244a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b94e3e40e5b3648143a7359edd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9b97e1a0ea4e516b78c4c2774"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d0286e44d9f8264a5654e2908"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e73ac51e27bcbdcd69b04b3b8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e03a35937aac0e95c8e2044ace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f53d83210438a6f59c37f2d0bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50dc6b0d080b212e6c673eebd1"`);
        await queryRunner.query(`DROP TABLE "indexed_events"`);
        await queryRunner.query(`DROP TABLE "indexer_state"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df7123a42ef2f3e669efda22ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb2201163ed66e787e40ac52a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0c6f2e60a2224c2fd9731c683"`);
        await queryRunner.query(`DROP TABLE "aml_flags"`);
        await queryRunner.query(`DROP TYPE "public"."aml_flags_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."aml_flags_risklevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cf6121019cef068e24a0130ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5582c3140c9cdbc6e5f61e0577"`);
        await queryRunner.query(`DROP TABLE "kyc_documents"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20cefd620ec4e2ab8837079b9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffbd41c9c75a25e6c5e2332ae5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95d5fd0497c4395f8737a22f14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dc59243d0fc921b9f82074ffb"`);
        await queryRunner.query(`DROP TABLE "compliance_audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f71e34495dae27087b5773b35b"`);
        await queryRunner.query(`DROP TABLE "kyc_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_risklevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e9040aac7adaa82e79053c299"`);
        await queryRunner.query(`DROP TABLE "compliance_configs"`);
        await queryRunner.query(`DROP TYPE "public"."compliance_configs_region_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce56d3bfad4feb1d3252c51384"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_741a5a7010d0c03f8122d6d61b"`);
        await queryRunner.query(`DROP TABLE "dispute_evidence"`);
        await queryRunner.query(`DROP TYPE "public"."dispute_evidence_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a7db7f4151d049652d8fe5acc"`);
        await queryRunner.query(`DROP TABLE "arbitrators"`);
        await queryRunner.query(`DROP TYPE "public"."arbitrators_expertise_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3031a37a2cb313f668ed6fc69"`);
        await queryRunner.query(`DROP TABLE "dispute_timeline"`);
        await queryRunner.query(`DROP TYPE "public"."dispute_timeline_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ea46f4f2225f38d127063c367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bedde3922ec76bcc4b4c1bd93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da437e54ac24659ff46aff18c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c71270511d986442bb1813647a"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_resolutiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_classification_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e154dd9c8d78610a275b5c7253"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_288e9a3fe13cfe14abe9824e9c"`);
        await queryRunner.query(`DROP TABLE "dispute_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c4b06882bfec7bf138c7c8210"`);
        await queryRunner.query(`DROP TABLE "escrow_milestones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac5ba8dd168f451627bc6d1454"`);
        await queryRunner.query(`DROP TABLE "escrow_timeline"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_timeline_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e6c59b6f18eb94d687931f918"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f04f3909ee01de9a7ce65a50b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7640e3281b452444b4f80276cf"`);
        await queryRunner.query(`DROP TABLE "escrow_signatories"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_signatories_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fb90845036be42987113ab96d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_058dc076c4c41196ed086f0fa0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d63194481c463866b27b3c27ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc65c37fb330fa0139e9fb7cbc"`);
        await queryRunner.query(`DROP TABLE "escrow_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_accounts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_accounts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e849f726c62c2de31e5d83d0c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_018cf7e53f7919c324a7707da1"`);
        await queryRunner.query(`DROP TABLE "arbitrage_opportunities"`);
        await queryRunner.query(`DROP TYPE "public"."arbitrage_opportunities_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9859e6b4f69f733f09e017f1e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8073479b36f9a5ead3a3616be3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98ae24c5ad8e4c6200ea1a9856"`);
        await queryRunner.query(`DROP TABLE "liquidity_pools"`);
        await queryRunner.query(`DROP TYPE "public"."liquidity_pools_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."liquidity_pools_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da34a0d6d76e251178eafd6fa2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc877deab8cfea090c3362941"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_219067801fd908ef27703700d2"`);
        await queryRunner.query(`DROP TABLE "route_cache"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb475b7f6c9b1df88b2c73927e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c99674591cdfaff0b17390aead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfc3f3efdd5ef21c496d293118"`);
        await queryRunner.query(`DROP TABLE "notification_analytics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f98bcad411bf7ef524165171f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de11429da99c117cdfeff5ec17"`);
        await queryRunner.query(`DROP TABLE "pool_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c98f5cd679fefeebac9ca98c7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a65b771bc8228047f2f78a091"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc562bb50c44337df593cc14b3"`);
        await queryRunner.query(`DROP TABLE "listings"`);
        await queryRunner.query(`DROP TYPE "public"."listings_status_enum"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_subscribedtypes_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30a545561c0718deb8390447a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df959b33c1ba4ad9ff2dc3c487"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5097ae6510fafaebc7c8b352c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e90d958270f67459f0663d52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f32aebbf93c81e2e656c8a6bad"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_deliverystatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b69b3c3eb6503a959e90ce8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35bee2c1e38cf9298c2a503340"`);
        await queryRunner.query(`DROP TABLE "portfolio_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9161d79952698317f770873796"`);
        await queryRunner.query(`DROP TABLE "rate_limit_configs"`);
        await queryRunner.query(`DROP TYPE "public"."rate_limit_configs_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22feaf5fae928f9b0a49907927"`);
        await queryRunner.query(`DROP TABLE "audit_trails"`);
        await queryRunner.query(`DROP TYPE "public"."audit_trails_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eadbc13a7dc33dfb702b14534e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_side_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37b1e010986c8656a127475397"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_114382727542adba2d2b90e0a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c674f97aaa8efd9582297a149"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_423f3e8be79b7467f04d2466db"`);
        await queryRunner.query(`DROP TABLE "trades"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c484ae61066d9fbae721664c2"`);
        await queryRunner.query(`DROP TABLE "batch_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."batch_audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_batches_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_batches_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6450098cfd48ef3437b4fe360"`);
        await queryRunner.query(`DROP TABLE "transaction_batches"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_batches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_legs_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_legs_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34f326691e930a01d56953e5ed"`);
        await queryRunner.query(`DROP TABLE "batch_legs"`);
        await queryRunner.query(`DROP TYPE "public"."batch_legs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_user_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da87c55b3bbbe96c6ed88ea7ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bb58f2b6e30cb51a6504599f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_256c7960dace26f2f271124dce"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8504b7f392f6da1ee6a52d076"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96733ba6989bd2ef3d3c075123"`);
        await queryRunner.query(`DROP TABLE "multisig_signatures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_168f1b91c2b550b587e9dd24f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6f542393aa19a51323cecd3f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f27a53a4d2745de8a37dea0646"`);
        await queryRunner.query(`DROP TABLE "multisig_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."multisig_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."multisig_transactions_thresholdcategory_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84f794a0022d98193d9448d245"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4b28a2c4b8bd96cce38ce2c6d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16f897a9887e4372561fdcc155"`);
        await queryRunner.query(`DROP TABLE "webhook_deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_deliveries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e54e4e4200f7a74cbbdf764f51"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_subscriptions_status_enum"`);
    }

}
