export enum EscrowTimelineEventType {
  ESCROW_CREATED = 'escrow_created',
  SIGNATORY_ADDED = 'signatory_added',
  SIGNATORY_APPROVED = 'signatory_approved',
  SIGNATORY_REVOKED = 'signatory_revoked',
  ESCROW_FUNDED = 'escrow_funded',
  MILESTONE_ADDED = 'milestone_added',
  MILESTONE_COMPLETED = 'milestone_completed',
  PARTIAL_RELEASE = 'partial_release',
  ESCROW_SETTLED = 'escrow_settled',
  ESCROW_REFUNDED = 'escrow_refunded',
  ESCROW_EXPIRED = 'escrow_expired',
  ESCROW_CANCELLED = 'escrow_cancelled',
  DISPUTE_FLAGGED = 'dispute_flagged',
  DISPUTE_RESOLVED = 'dispute_resolved',
  TIMEOUT_TRIGGERED = 'timeout_triggered',
  SIGNATURE_THRESHOLD_REACHED = 'signature_threshold_reached',
}
